pipeline {
    agent any

    environment {
        ARM_CLIENT_ID        = credentials('ARM_CLIENT_ID')
        ARM_CLIENT_SECRET    = credentials('ARM_CLIENT_SECRET')
        ARM_SUBSCRIPTION_ID  = credentials('ARM_SUBSCRIPTION_ID')
        ARM_TENANT_ID        = credentials('ARM_TENANT_ID')
    }

    stages {  

        stage('Values Defining') {
            steps {
                echo 'ARM_CLIENT_ID'
            }
        }      

        stage('Terraform Init') {
            steps {
                dir ('/Terraform')
                sh 'terraform init'
            }
        }

        stage('Terraform Plan') {
            steps {
                dir ('/Terraform')
                sh 'terraform plan -out=tfplan'
            }
        }

        stage('Terraform Apply') {
            steps {
                dir ('/Terraform')
                input message: 'Approve to apply Terraform changes?'
                sh 'terraform apply tfplan'
            }
        }
    }

    post {
        always {		  
            cleanWs()       
    }
}

}